// Sections 31 à 43 du guide CabaLink (transcription fidèle, FR + AR).
import 'cabalink_guide_content.dart';

final List<CabalinkGuideSection> cabalinkGuideSectionsPart3 = [
  sec(
    31,
    "Commission avec un ambassadeur",
    "العمولة عند وجود سفير",
    [
      par("Lorsque le voyage a été apporté par un ambassadeur CabaLink, la commission totale reste :"),
      frm(["2 €/kg"]),
      par("Elle est alors divisée à parts égales :"),
      bul([
        "1 €/kg pour CabaLink",
        "1 €/kg pour l’ambassadeur",
      ]),
      par("Pour 60 kg :"),
      frm(["60 × 1 € × 270 = 16 200 DZD"]),
      par("Donc :"),
      tbl(
        ["Partie", "Montant"],
        [
          ["Transporteur", "300 000 DZD"],
          ["CabaLink", "16 200 DZD"],
          ["Ambassadeur", "16 200 DZD"],
          ["Client", "332 400 DZD"],
        ],
      ),
      par("La présence d’un ambassadeur ne diminue pas le montant du transporteur."),
    ],
    [
      par("إذا كانت الرحلة قد جاءت عن طريق سفير CabaLink، تبقى العمولة الإجمالية نفسها:"),
      frm(["2€/كغ"]),
      par("لكنها تقسم بين CabaLink والسفير بالتساوي:"),
      bul([
        "1€/كغ لـ CabaLink.",
        "1€/كغ للسفير.",
      ]),
      par("في مثال 60 كغ:"),
      frm(["60 × 1€ × 270 = 16,200 دج"]),
      par("إذن:"),
      tbl(
        ["الطرف", "المبلغ"],
        [
          ["الناقل", "300,000 دج"],
          ["CabaLink", "16,200 دج"],
          ["السفير", "16,200 دج"],
          ["العميل", "332,400 دج"],
        ],
      ),
      par("ولا يتغير سعر الناقل بسبب وجود السفير."),
    ],
  ),
  sec(
    32,
    "L’ambassadeur CabaLink",
    "السفير",
    [
      par("L’ambassadeur est une personne qui contribue à développer le réseau CabaLink en faisant venir de nouveaux transporteurs."),
      par("Chaque ambassadeur dispose d’un code de parrainage."),
      par(
        "Lorsqu’un transporteur rejoint CabaLink grâce à ce code et qu’une opération éligible est réalisée, l’ambassadeur peut recevoir sa part de commission selon les règles du programme.",
      ),
      par("Part de l’ambassadeur :"),
      par("50 % de la commission CabaLink applicable aux opérations qu’il a apportées."),
      frm([
        "Avec une commission totale de 2 €/kg : 1 €/kg pour l’ambassadeur et 1 €/kg pour CabaLink.",
      ]),
    ],
    [
      par("السفير هو شخص يساعد CabaLink على جلب ناقلين جدد."),
      par("يحصل كل سفير على رمز إحالة خاص به."),
      par(
        "عندما ينضم ناقل من خلال رمز السفير وتتحقق شروط الرحلة المؤهلة، يحصل السفير على حصته من العمولة.",
      ),
      par("حصة السفير:"),
      bul([
        "50% من عمولة CabaLink المخصصة للرحلات التي أحالها.",
        "وبما أن العمولة الإجمالية هي 2€/كغ:",
        "1€/كغ للسفير",
        "1€/كغ لـ CabaLink",
      ]),
    ],
  ),
  sec(
    33,
    "Activité de l’ambassadeur",
    "نشاط السفير",
    [
      par("L’ambassadeur n’est pas uniquement chargé de partager un lien."),
      par("Dans le modèle défini :"),
      par("Après chaque 3 voyages apportés, l’ambassadeur réalise :"),
      frm([
        "3 publicités ou vidéos",
        "sur 3 plateformes sociales différentes",
      ]),
      par(
        "afin de contribuer au développement de la communauté CabaLink et à l’acquisition de nouveaux utilisateurs et transporteurs.",
      ),
    ],
    [
      par("دور السفير ليس مجرد إرسال رابط."),
      par("من ضمن نموذج النشاط المتفق عليه:"),
      par("بعد كل 3 رحلات تم جلبها عبره، يقوم السفير بإنشاء:"),
      frm([
        "3 إعلانات أو فيديوهات",
        "على 3 منصات اجتماعية مختلفة",
      ]),
      par("وذلك للمساعدة في توسيع شبكة CabaLink وجلب المزيد من المستخدمين والناقلين."),
    ],
  ),
  sec(
    34,
    "Pourquoi le système d’ambassadeurs ?",
    "لماذا نموذج السفير مهم؟",
    [
      par("L’ambassadeur permet à CabaLink de construire progressivement un réseau international de transporteurs."),
      par(
        "Au lieu de dépendre uniquement de la publicité classique, les utilisateurs peuvent participer directement au développement du réseau.",
      ),
      par("Plus le réseau de transporteurs grandit, plus les clients peuvent disposer de choix concernant :"),
      bul([
        "les destinations ;",
        "les dates ;",
        "les poids ;",
        "les prix.",
      ]),
    ],
    [
      par("السفير يساعد على بناء شبكة محلية ودولية من الناقلين."),
      par("بدل أن تعتمد CabaLink على الإعلانات فقط، يستطيع المستخدمون أنفسهم المساهمة في توسيع الشبكة."),
      par("كلما توسعت شبكة الناقلين، أصبح لدى العملاء خيارات أكثر من حيث:"),
      bul([
        "الوجهات.",
        "التواريخ.",
        "الوزن.",
        "الأسعار.",
      ]),
    ],
  ),
  sec(
    35,
    "Partenariats",
    "الشراكات",
    [
      par("CabaLink peut établir des partenariats avec :"),
      bul([
        "des entreprises logistiques ;",
        "des sociétés de transport ;",
        "des entreprises de livraison locale ;",
        "des entreprises technologiques ;",
        "des entreprises commerciales ;",
        "d’autres organisations pouvant apporter une valeur au réseau.",
      ]),
      par("Cependant, le partenaire n’est pas un rôle obligatoire dans une opération de transport."),
      par("Le fonctionnement principal reste :"),
      frm(["Client ↔ Transporteur ↔ CabaLink"]),
      par("avec éventuellement :"),
      frm(["Ambassadeur → Transporteur"]),
      par("dans le cadre du parrainage."),
    ],
    [
      par("يمكن لـ CabaLink الدخول في شراكات مع:"),
      bul([
        "شركات لوجستية.",
        "شركات نقل.",
        "شركات توصيل محلية.",
        "شركات تقنية.",
        "جهات تجارية.",
        "جهات أخرى يمكنها تقديم قيمة للمنصة.",
      ]),
      par("لكن الشريك ليس دورًا أساسيًا داخل عملية CabaLink."),
      par("العملية الأساسية تبقى بين:"),
      frm(["العميل ↔ الناقل ↔ CabaLink"]),
      par("مع إمكانية وجود السفير كطرف إحالة."),
    ],
  ),
  sec(
    36,
    "Évolution de la plateforme",
    "التحديثات المستمرة",
    [
      par("CabaLink est conçue pour évoluer."),
      par("De nouvelles fonctionnalités peuvent être ajoutées en fonction :"),
      bul([
        "des demandes des utilisateurs ;",
        "des besoins du marché ;",
        "des exigences de sécurité ;",
        "des évolutions réglementaires ;",
        "des améliorations techniques.",
      ]),
      par("Les utilisateurs doivent maintenir l’application à jour afin de bénéficier des nouvelles fonctionnalités."),
    ],
    [
      par("CabaLink ليست منصة ثابتة."),
      par("يمكن إضافة وظائف جديدة بناءً على:"),
      bul([
        "اقتراحات المستخدمين.",
        "احتياجات السوق.",
        "متطلبات الأمان.",
        "التغيرات القانونية.",
        "تحسين تجربة المستخدم.",
      ]),
      par("لذلك يجب على المستخدمين تحديث التطبيق باستمرار للاستفادة من آخر الوظائف والتحديثات."),
    ],
  ),
  sec(
    37,
    "Cycle complet d’une opération",
    "دورة العملية الكاملة",
    [
      par("Le parcours général est :"),
      dgm([
        "Le transporteur crée son compte",
        "Il vérifie son identité, s’il souhaite un compte entièrement vérifié",
        "Il crée son voyage",
        "Il indique la date, la destination, le poids disponible et son prix",
        "Il publie et partage son voyage sur les réseaux sociaux",
        "Le client recherche un voyage",
        "Le client choisit un transporteur",
        "Les parties définissent les conditions",
        "Le point de collecte est défini",
        "La marchandise arrive au point de collecte",
        "Le transporteur inspecte la marchandise",
        "Il vérifie les produits interdits ou réglementés",
        "La marchandise est photographiée et documentée",
        "Le transporteur accepte la marchandise",
        "Le poids est réservé",
        "Le transporteur voyage",
        "Les étapes nécessaires sont documentées",
        "La marchandise arrive à destination",
        "L’identité du destinataire est vérifiée",
        "La marchandise est livrée et la livraison est documentée",
        "Le client paie le transporteur à la livraison",
        "L’opération est clôturée et les utilisateurs peuvent s’évaluer",
      ]),
    ],
    [
      par("يمكن تلخيص رحلة العملية بالشكل التالي:"),
      dgm([
        "الناقل ينشئ حسابًا",
        "يتحقق من هويته، إن أراد التوثيق الكامل",
        "يضيف رحلته",
        "يحدد التاريخ والوجهة والوزن والسعر",
        "ينشر الرحلة ويشاركها على الشبكات الاجتماعية",
        "العميل يبحث عن الرحلة",
        "العميل يختار الناقل",
        "يتم الاتفاق على التفاصيل",
        "يتم تحديد نقطة التجميع",
        "تصل البضاعة إلى الناقل",
        "الناقل يفحص البضاعة",
        "يتم التأكد من عدم وجود منتجات ممنوعة أو مقيدة",
        "يتم تصوير البضاعة وتوثيق استلامها",
        "الناقل يوافق عليها",
        "يتم حجز الوزن",
        "الناقل يسافر",
        "يتم توثيق المراحل المطلوبة",
        "تصل البضاعة إلى الوجهة",
        "يتم التحقق من هوية المستلم",
        "يتم تسليم البضاعة وتوثيق التسليم",
        "العميل يدفع للناقل عند الاستلام",
        "يتم إغلاق العملية وتقييم الطرفين",
      ]),
    ],
  ),
  sec(
    38,
    "Valeur économique de CabaLink",
    "القيمة الاقتصادية للمنصة",
    [
      par("Chaque partie peut bénéficier du modèle :"),
      bul([
        "Le client — Il dispose d’une solution alternative pour transporter ses marchandises à l’international et peut rechercher une combinaison adaptée de prix, date, destination et poids.",
        "Le transporteur — Il peut transformer une partie de son poids disponible en revenu supplémentaire.",
        "Le micro-importateur — Il peut utiliser ses voyages et sa capacité de transport pour générer un revenu supplémentaire.",
        "L’ambassadeur — Il peut générer des revenus en développant le réseau de transporteurs.",
        "CabaLink — La plateforme reçoit une commission par kilogramme transporté selon son modèle économique.",
      ]),
    ],
    [
      par("CabaLink تنشئ نموذجًا يستفيد فيه كل طرف من دوره:"),
      bul([
        "العميل — يحصل على وسيلة بديلة للنقل الدولي وقد يجد رحلة مناسبة من حيث السعر والتاريخ والوجهة والوزن.",
        "الناقل — يستطيع تحويل الوزن المتاح في رحلته إلى دخل إضافي.",
        "المستورد المصغر — يمكنه استغلال رحلاته وقدرته على نقل السلع لتحقيق دخل إضافي.",
        "السفير — يمكنه تحقيق دخل من خلال جلب ناقلين مؤهلين إلى المنصة.",
        "CabaLink — تحصل على عمولة محددة لكل كيلوغرام يتم نقله وفق نموذج المنصة.",
      ]),
    ],
  ),
  sec(
    39,
    "Les principes fondamentaux",
    "المبادئ الأساسية لـ CabaLink",
    [
      par("Le modèle CabaLink repose notamment sur :"),
      bul([
        "Confiance — Grâce à la vérification, aux évaluations et à la documentation.",
        "Transparence — Grâce à l’enregistrement des accords, des prix et des étapes.",
        "Traçabilité — Grâce au suivi de l’opération.",
        "Sécurité — Grâce à la vérification des utilisateurs, des marchandises et des documents.",
        "Valorisation du poids — Grâce à la transformation d’un poids inutilisé en opportunité économique.",
        "Flexibilité — Grâce à plusieurs transporteurs, voyages et dates disponibles.",
        "Confidentialité — Grâce à la protection des documents d’identité et des informations sensibles.",
      ]),
    ],
    [
      par("يقوم النموذج على مجموعة من المبادئ:"),
      bul([
        "الثقة — من خلال التحقق والتقييم والتوثيق.",
        "الشفافية — من خلال تسجيل الاتفاقات والأسعار ومراحل العملية.",
        "التتبع — من خلال متابعة مراحل البضاعة.",
        "الأمان — من خلال التحقق من المستخدمين والبضائع والوثائق.",
        "استغلال الوزن — من خلال تحويل الوزن غير المستغل إلى فرصة اقتصادية.",
        "المرونة — من خلال تعدد الرحلات والناقلين والتواريخ.",
        "الخصوصية — من خلال حماية وثائق الهوية والمعلومات الحساسة.",
      ]),
    ],
  ),
  sec(
    40,
    "Ce qui distingue CabaLink",
    "ما يميز CabaLink",
    [
      par("CabaLink n’est pas simplement un espace où publier une annonce de voyage."),
      par("La plateforme regroupe :"),
      bul([
        "les voyages ;",
        "le poids disponible ;",
        "les clients ;",
        "les transporteurs ;",
        "la vérification ;",
        "la documentation ;",
        "les photographies ;",
        "le suivi ;",
        "l’évaluation ;",
        "le signalement ;",
        "le paiement à la livraison ;",
        "le système d’ambassadeurs ;",
        "les partenariats ;",
        "le transport international.",
      ]),
      par(
        "L’objectif est de rendre le transport de marchandises via les voyageurs plus organisé, documenté, transparent et traçable.",
      ),
    ],
    [
      par("CabaLink ليست مجرد مكان لنشر إعلان عن رحلة."),
      par("إنها منظومة تجمع بين:"),
      bul([
        "الرحلات.",
        "الوزن المتاح.",
        "العملاء.",
        "الناقلين.",
        "التحقق.",
        "التوثيق.",
        "الصور.",
        "التتبع.",
        "التقييم.",
        "الإبلاغ.",
        "الدفع عند الاستلام.",
        "الإحالة والسفراء.",
        "الشراكات.",
        "النقل الدولي.",
      ]),
      par("والهدف هو جعل عملية نقل البضائع عبر المسافرين أكثر تنظيمًا ووضوحًا وقابلية للتتبع."),
    ],
  ),
  sec(
    41,
    "Définition officielle courte",
    "التعريف الرسمي المختصر",
    [
      par(
        "CabaLink est une plateforme de transport international qui met en relation les clients avec des voyageurs, micro-importateurs et transporteurs capables de transporter leurs marchandises, tout en proposant la publication des voyages et du poids disponible, la vérification des utilisateurs, la documentation des marchandises, le suivi des étapes, la confirmation de réception et l’évaluation, avec un système de commission transparent et un programme d’ambassadeurs.",
      ),
    ],
    [
      par(
        "CabaLink هي منصة للنقل الدولي تربط العملاء بالمسافرين والمستوردين المصغرين والناقلين القادرين على نقل بضائعهم، مع توفير نشر الرحلات والوزن المتاح، التحقق من المستخدمين، توثيق البضائع، تتبع مراحل العملية، إثبات الاستلام والتسليم، والتقييم، مع نظام عمولة واضح وبرنامج سفراء للإحالة.",
      ),
    ],
  ),
  sec(
    42,
    "L’équation CabaLink",
    "المعادلة الأساسية لـ CabaLink",
    [
      par("Voyage + poids disponible + client + transporteur + documentation + suivi = opération de transport organisée"),
      par("Modèle financier :"),
      frm([
        "Prix fixé par le transporteur + 2 €/kg de commission CabaLink = prix final client",
        "Avec ambassadeur : 2 €/kg = 1 €/kg pour CabaLink + 1 €/kg pour l’ambassadeur",
        "Taux de change de référence : 1 € = 270 DZD",
      ]),
    ],
    [
      par("رحلة + وزن متاح + عميل + ناقل + توثيق + تتبع = عملية نقل منظمة"),
      par("والجانب الاقتصادي:"),
      frm([
        "الناقل يحدد سعره + CabaLink تضيف 2€/كغ = السعر النهائي للعميل",
        "وعند وجود سفير: 2€/كغ = 1€/كغ لـ CabaLink + 1€/كغ للسفير",
        "مع اعتماد: 1€ = 270 دج",
      ]),
    ],
  ),
  sec(
    43,
    "Conclusion",
    "الخلاصة",
    [
      par(
        "CabaLink vise à transformer le poids disponible lors des voyages internationaux en une ressource pouvant générer un revenu, tout en créant un système organisé reliant les clients aux transporteurs.",
      ),
      par("Le transporteur fixe son prix."),
      par("Le client voit le prix final."),
      par("CabaLink ajoute sa commission."),
      par("L’ambassadeur reçoit sa part lorsqu’il apporte des opérations éligibles."),
      par(
        "L’ensemble du processus est renforcé par la vérification, la documentation, les photographies, le suivi, l’évaluation et la preuve de livraison.",
      ),
      par(
        "CabaLink = une plateforme qui relie le voyage, le poids disponible et la demande, avec documentation, suivi et confiance.",
      ),
    ],
    [
      par(
        "CabaLink تهدف إلى تحويل الوزن المتاح في الرحلات الدولية إلى مورد يمكن استغلاله، مع إنشاء نظام يربط العميل بالناقل بطريقة منظمة.",
      ),
      par("الناقل يحدد سعره."),
      par("العميل يرى السعر النهائي."),
      par("CabaLink تضيف عمولتها."),
      par("السفير يحصل على حصته عند إحالة الرحلات المؤهلة."),
      par("والعملية يتم دعمها بالتحقق والتوثيق والتصوير والتتبع والتقييم."),
      par(
        "CabaLink = منصة تربط الرحلة بالوزن والطلب، وتضيف إليها التوثيق والتتبع والثقة.",
      ),
    ],
  ),
];