// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwB45_WiSmsUVO04cg8IuHBoK53wRBYo4',
    appId: '1:41156395312:web:609708fa93febda5f208f5',
    messagingSenderId: '41156395312',
    projectId: 'cargolink-23dd3',
    authDomain: 'cargolink-23dd3.firebaseapp.com',
    storageBucket: 'cargolink-23dd3.firebasestorage.app',
    measurementId: 'G-99NJC761GS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxwN7Z-wQi-6rwEcMGM75P8wRj9daPsxs',
    appId: '1:41156395312:android:85408005823586eef208f5',
    messagingSenderId: '41156395312',
    projectId: 'cargolink-23dd3',
    storageBucket: 'cargolink-23dd3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOlS50UvagD8YEw8SRsDFHlsAijkYL2y4',
    appId: '1:41156395312:ios:41ebcfa63dc5003bf208f5',
    messagingSenderId: '41156395312',
    projectId: 'cargolink-23dd3',
    storageBucket: 'cargolink-23dd3.firebasestorage.app',
    iosBundleId: 'com.cargolink.dz.cargolink',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOlS50UvagD8YEw8SRsDFHlsAijkYL2y4',
    appId: '1:41156395312:ios:41ebcfa63dc5003bf208f5',
    messagingSenderId: '41156395312',
    projectId: 'cargolink-23dd3',
    storageBucket: 'cargolink-23dd3.firebasestorage.app',
    iosBundleId: 'com.cargolink.dz.cargolink',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBwB45_WiSmsUVO04cg8IuHBoK53wRBYo4',
    appId: '1:41156395312:web:1c65610b1ff74774f208f5',
    messagingSenderId: '41156395312',
    projectId: 'cargolink-23dd3',
    authDomain: 'cargolink-23dd3.firebaseapp.com',
    storageBucket: 'cargolink-23dd3.firebasestorage.app',
    measurementId: 'G-FGMR0JJZV9',
  );
}
